[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10.2.4"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
