[build]
  command = "npm install --legacy-peer-deps && CI=false npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "10.2.4"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
