[build]
  command = "CI=false npm install --legacy-peer-deps --no-optional && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.16.0"
  NPM_VERSION = "9.5.1"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
